version: '3.8'

services:

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - animes-volume:/data/db

  mongo-ui:
    container_name: mongo-ui
    image: mongo-express:latest
    restart: always
    ports:
      - '27000:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on:
      - mongo

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: fanime-credentials
    volumes:
      - credentials-volume:/var/lib/postgresql/data

  discovery-service:
    container_name: discovery-service
    build:
      context: discovery-service
      dockerfile: Dockerfile
    ports:
      - '8761:8761'

  api-gateway-service:
    container_name: api-gateway-service
    build:
      context: api-gateway-service
      dockerfile: Dockerfile
    ports:
      - '8765:8765'
    environment:
      DISCOVERY_URL: http://discovery-service:8761/eureka
    depends_on:
      - discovery-service

  auth-service:
    container_name: auth-service
    build:
      context: auth-service
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/fanime-credentials
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      DISCOVERY_URL: http://discovery-service:8761/eureka
    depends_on:
      - postgres
      - discovery-service
      - api-gateway-service

  anime-service:
    container_name: anime-service
    build:
      context: anime-service
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      MONGODB_USER: root
      MONGODB_PASS: root
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      DISCOVERY_URL: http://discovery-service:8761/eureka
    depends_on:
      - mongo
      - discovery-service
      - api-gateway-service

volumes:
  credentials-volume:
  animes-volume:
