spring:
  application:
    name: anime-ms
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: fanime
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
