apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service-app
  labels:
    app: api-gateway-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service-app
  template:
    metadata:
      labels:
        app: api-gateway-service-app
    spec:
      containers:
        - name: api-gateway-service-app
          image: stempz/fanime-api-gateway-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8765
          env:
            - name: DISCOVERY_HOST
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_host
            - name: DISCOVERY_URL
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service-svc
spec:
  type: LoadBalancer
  selector:
    app: api-gateway-service-app
  ports:
    - port: 80
      targetPort: 8765
      protocol: TCP
