apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-cm
data:
  postgres_url: jdbc:postgresql://auth-service-db-postgresql:5432/fanime-creds
  postgres_user: postgres

---

apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
data:
  postgres-password: cm9vdA==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-app
  labels:
    app: auth-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-app
  template:
    metadata:
      labels:
        app: auth-service-app
    spec:
      containers:
        - name: auth-service-app
          image: stempz/fanime-auth-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-service-cm
                  key: postgres_url
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: auth-service-cm
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: postgres-password
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: kafka-cm
                  key: kafka_svc
            - name: DISCOVERY_HOST
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_host
            - name: DISCOVERY_URL
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc
spec:
  selector:
    app: auth-service-app
  ports:
    - port: 80
      targetPort: 8080
