server:
  port: 8081
spring:
  datasource:
    url: "${POSTGRES_URL:jdbc:postgresql://localhost:5432/fanime-users}"
    username: "${POSTGRES_USER:postgres}"
    password: "${POSTGRES_PASSWORD:root}"
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
