server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: "${POSTGRES_URL:jdbc:postgresql://localhost:5432/fanime-users}"
    username: "${POSTGRES_USER:postgres}"
    password: "${POSTGRES_PASSWORD:root}"
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: "${DISCOVERY_URL:http://localhost:8761/eureka}"
management:
  endpoints:
    web:
      exposure:
        include: info,health
