server:
  port: 8761
spring:
  application:
    name: discovery-service
eureka:
  instance:
    hostname: "${DISCOVERY_HOST:eureka}"
  client:
    register-with-eureka: false
    fetch-registry: false
