spring:
  application:
    name: gateway-ms
  cloud:
    gateway:
      routes:
        - id: anime-ms-route
          uri: lb://anime-ms
          predicates:
            - Path=/animes/**
          filters:
            - PrefixPath=/api/v1
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
