server:
  port: 8081
spring:
  application:
    name: anime-service
  data:
    mongodb:
      uri: "mongodb://${MONGODB_USER:root}:${MONGODB_PASS:example}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}"
      database: fanime-animes
eureka:
  client:
    service-url:
      defaultZone: "${DISCOVERY_URL:http://localhost:8761/eureka}"
management:
  endpoints:
    web:
      exposure:
        include: info,health
