server:
  port: 8081
spring:
  application:
    name: anime-service
  data:
    mongodb:
      uri: "mongodb://${MONGODB_USER:root}:${MONGODB_PASS:example}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}"
      database: fanime-animes
      auto-index-creation: true
eureka:
  instance:
    preferIpAddress: true
    ip-address: "${DISCOVERY_HOST:localhost}"
  client:
    service-url:
      defaultZone: "${DISCOVERY_URL:http://localhost:8761/eureka}"
app:
  security:
    secret-key: "2A472D4A614E645267556B58703273357638792F423F4528482B4D6250655368"
management:
  endpoints:
    web:
      exposure:
        include: info,health
logging:
  level:
    org.springframework.security: DEBUG
