server:
  port: 8080
spring:
  data:
    mongodb:
      uri: "mongodb://${MONGODB_USER:root}:${MONGODB_PASS:example}@mongo:27017"
      database: fanime-animes
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
