server:
  port: 8765
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service-authenticate
          uri: lb://auth-service
          predicates:
            - Path=/auth/authenticate
            - Method=POST
          filters:
            - PrefixPath=/api/v1

        - id: auth-service-register
          uri: lb://auth-service
          predicates:
            - Path=/auth/register
            - Method=POST
          filters:
            - PrefixPath=/api/v1

        - id: auth-service-verify
          uri: lb://auth-service
          predicates:
            - Path=/auth/verify
            - Method=GET
          filters:
            - PrefixPath=/api/v1

        - id: auth-service-forgot-password
          uri: lb://auth-service
          predicates:
            - Path=/auth/forgot-password
            - Method=POST
          filters:
            - PrefixPath=/api/v1

        - id: auth-service-reset-password
          uri: lb://auth-service
          predicates:
            - Path=/auth/reset-password
            - Method=POST
          filters:
            - PrefixPath=/api/v1

        - id: anime-service-anime-create
          uri: lb://anime-service
          predicates:
            - Path=/anime
            - Method=POST
          filters:
            - PrefixPath=/api/v1/secured

        - id: anime-service-genres-get-all
          uri: lb://anime-service
          predicates:
            - Path=/genres
            - Method=GET
          filters:
            - PrefixPath=/api/v1

        - id: anime-service-genres-create
          uri: lb://anime-service
          predicates:
            - Path=/genres
            - Method=POST
          filters:
            - PrefixPath=/api/v1/secured
            - AuthenticationFilter

        - id: anime-service-studios-get-all
          uri: lb://anime-service
          predicates:
            - Path=/studios
            - Method=GET
          filters:
            - PrefixPath=/api/v1

        - id: anime-service-studios-create
          uri: lb://anime-service
          predicates:
            - Path=/studios
            - Method=POST
          filters:
            - PrefixPath=/api/v1/secured
            - AuthenticationFilter
eureka:
  instance:
    preferIpAddress: true
    hostname: "${DISCOVERY_HOST:eureka}"
  client:
    service-url:
      defaultZone: "${DISCOVERY_URL:http://localhost:8761/eureka}"
management:
  endpoints:
    web:
      exposure:
        include: info,health
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
