server:
  port: 8765
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service-authenticate
          uri: lb://auth-service
          predicates:
            - Path=/auth/authenticate
            - Method=POST
          filters:
            - PrefixPath=/api/v1

        - id: auth-service-register
          uri: lb://auth-service
          predicates:
            - Path=/auth/register
            - Method=POST
          filters:
            - PrefixPath=/api/v1

        - id: anime-service-get-all
          uri: lb://anime-service
          predicates:
            - Path=/anime
            - Method=GET
          filters:
            - PrefixPath=/api/v1
eureka:
  client:
    service-url:
      defaultZone: "${DISCOVERY_URL:http://localhost:8761/eureka}"
management:
  endpoints:
    web:
      exposure:
        include: info,health
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
