server:
  port: 8765
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: anime-service-route
          uri: lb://anime-service
          predicates:
            - Path=/animes/**
          filters:
            - PrefixPath=/api/v1
eureka:
  client:
    service-url:
      defaultZone: "${DISCOVERY_URL:http://localhost:8761/eureka}"
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
